language: python

python:
  - 3.6

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run nosetests --with-doctest
  - pipenv run black megyr/*.py --check
  - pipenv run mypy megyr/*.py --ignore-missing-imports --strict
